import { MonsterTemplate } from "./monsterTypes"

export const monsterDatabase: MonsterTemplate[] = [
  {
    id: "goblin",
    name: "고블린",
    level: 1,
    rarity: "normal",
    regions: ["pandora_maze"],
    maxHp: 15,
    attackMin: 1,
    attackMax: 4,
    exp: 10,
    gold: 5,
  },
  {
    id: "wolf",
    name: "늑대",
    level: 2,
    rarity: "normal",
    regions: ["pandora_maze", "forest_of_soul"],
    maxHp: 20,
    attackMin: 2,
    attackMax: 5,
    exp: 15,
    gold: 8,
  },
  {
    id: "skeleton",
    name: "스켈레톤",
    level: 3,
    rarity: "normal",
    regions: ["pandora_maze"],
    maxHp: 24,
    attackMin: 3,
    attackMax: 6,
    exp: 20,
    gold: 10,
  },
  {
    id: "venom_spider",
    name: "독거미",
    level: 4,
    rarity: "elite",
    regions: ["forest_of_soul"],
    maxHp: 30,
    attackMin: 4,
    attackMax: 8,
    exp: 35,
    gold: 18,
  },
]